Consistent empty tuples in IR
ethereum/fe pull request #406
Opened 2021-05-12 03:14 UTC by g-r-a-n-t

### What was wrong?

### How was it fixed?

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] OPTIONAL: Update [Spec](https://github.com/ethereum/fe/blob/master/docs/src/spec/index.md) if applicable
- [ ] Add entry to the [release notes](https://github.com/ethereum/fe/blob/master/newsfragments/README.md) (may forgo for trivial changes)

- [ ] Clean up commit history

2021-05-12 18:15 UTC, g-r-a-n-t commented
decided Im going to hold off on this and wait for zero-sized structs so we can full implement tuple lowering

2021-05-14 20:01 UTC, g-r-a-n-t commented on parser/src/grammar/types.rs
> +            Some(s) => {
remove debugging

2021-05-14 20:01 UTC, g-r-a-n-t commented on parser/tests/cases/parse_ast.rs
> +test_parse! { empty_struct_def, types::parse_struct_def, r#"struct S:
add pass for events and contracts

2021-05-14 20:01 UTC, g-r-a-n-t commented on test.fe
> +contract Ownable:
delete this

2021-05-14 22:59 UTC, g-r-a-n-t commented on compiler/src/lowering/mappers/functions.rs
> +                            func: Box::new(fe::Expr::Name("empty_tuple".to_string()).into_node()),
cleanup

2021-05-14 22:59 UTC, g-r-a-n-t commented on compiler/src/lowering/mappers/functions.rs
> +                    .unwrap_or(names::tuple_struct_type_desc(&Tuple::empty()).into_node()),
cleanup

2021-05-17 23:34 UTC, g-r-a-n-t commented on analyzer/src/context.rs
> -    pub fn is_empty_tuple(&self) -> bool {
update docs

2021-05-17 23:34 UTC, g-r-a-n-t commented on analyzer/src/namespace/types.rs
> +    pub fn is_empty_tuple(&self) -> bool {
add docs

2021-05-17 23:34 UTC, g-r-a-n-t commented on analyzer/src/namespace/types.rs
> +    pub fn is_empty(&self) -> bool {
fix docs

2021-05-17 23:34 UTC, g-r-a-n-t commented on analyzer/src/namespace/types.rs
>      pub fn is_empty_tuple(&self) -> bool {
add docs

2021-05-17 23:34 UTC, g-r-a-n-t commented on analyzer/src/namespace/types.rs
> +    pub fn is_empty(&self) -> bool {
docs

2021-05-17 23:34 UTC, g-r-a-n-t commented on analyzer/src/traversal/functions.rs
> +        if return_type.is_none() {
explain

2021-05-18 04:53 UTC, sbillig commented
@g-r-a-n-t It's maybe a bit late, but what if we introduce a Unit type (https://doc.rust-lang.org/std/primitive.unit.html) which just happens to resemble a tuple with no elements, and disallow empty tuples? We could use https://crates.io/crates/nonempty or https://crates.io/crates/vec1 to enforce the non-emptiness of the tuple elements vec.

That seems like a more aesthetically pleasing solution than lowering to an empty struct with a special name.

2021-05-18 15:49 UTC, g-r-a-n-t commented
@sbillig Yeah, I think that makes sense. The `is_empty_tuple` functions are also something that I'm not a big fan of.

I'd be happy to try it out in this PR.

2021-05-19 19:52 UTC, g-r-a-n-t commented on analyzer/src/namespace/types.rs
> +            FixedSize::Unit => "unit".to_string(),
should panic

2021-05-19 19:52 UTC, g-r-a-n-t commented on analyzer/src/namespace/types.rs
> +            .expect("empty tuple"),
better message

2021-05-19 19:52 UTC, g-r-a-n-t commented on analyzer/src/traversal/expressions.rs
> +            items: Vec1::try_from_vec(types_to_fixed_sizes(types)?).expect("emty tuple"),
better message

2021-05-19 19:52 UTC, g-r-a-n-t commented on compiler/src/lowering/mappers/functions.rs
> +            let mut lowered_body = multiple_stmts(context, body);
update docs

2021-05-19 19:52 UTC, g-r-a-n-t commented on compiler/src/yul/constructor.rs
> +        // init is given an empty tuple return during lowering, so we must pop it.
update all occurrences of "empty_tuple" or "empty tuple"

2021-05-19 19:52 UTC, g-r-a-n-t commented on compiler/src/yul/runtime/abi_dispatcher.rs
> +        let selection = selection_as_pop_statement(&attributes.name, &attributes.param_types());
explain with docs

2021-05-19 19:52 UTC, g-r-a-n-t commented on compiler/tests/cases/lowering/fixtures/return_empty_tuple_lowered.fe
> +contract Foo:
update the names of these files

2021-05-20 00:19 UTC, g-r-a-n-t commented
Added a unit type @sbillig, this is ready for a review.

2021-05-20 02:58 UTC, sbillig approved these changes
:+1:

2021-05-20 03:02 UTC, sbillig requested changes

2021-05-20 03:02 UTC, sbillig commented on newsfragments/406.internal.md
> +Empty tuples are lowered to an empty struct.
This should be updated

2021-05-20 04:23 UTC, sbillig approved these changes

2021-05-20 04:56 UTC, merged